[package]
name = "ledger-transport"
description = "Library to integrate with the Ledger apps"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Zondax GmbH <info@zondax.ch>"]
homepage = "https://github.com/Zondax/ledger-rs"
repository = "https://github.com/Zondax/ledger-rs"
readme = "README.md"
categories  = ["authentication", "cryptography"]
keywords = ["ledger", "nano", "apdu"]
edition     = "2018"
autobenches = false

[lib]
name = "ledger_transport"

[dependencies]
byteorder = "1.3"
lazy_static = "1.2"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

ledger-generic = { path = "../ledger-generic"}
# For not wasm compilation (native rust) compiling
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ledger-transport-hid = { path = "../ledger-transport-hid"}

# For wasm compiling
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"


[dev-dependencies]
sha2 = "0.8"

[profile.release]
overflow-checks = true
