[package]
name = "ledger-zondax-generic"
version = "0.1.0"
authors = ["Zondax GmbH <info@zondax.ch>"]
edition = "2018"

[lib]
name = "ledger_zondax_generic"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ledger-apdu = { path = "../ledger-apdu"}
ledger-transport = { path = "../ledger-transport"}
thiserror = "1.0"
